[update]
tasks = ["interfaces", "transform", "normalize"]

[update.interfaces]
path = "iOS"
defaultToBase = true

[update.transform]
codePath = "iOS"
localizablePath = "iOS/Supporting Files"
transformer = "swiftgenStructured"
supportedLanguageEnumPath = "iOS/Supporting Files"

[update.normalize]
path = "iOS"

[lint]
path = "iOS"
