language: objective-c
osx_image: xcode9.3
jobs:
  include:
    - stage: Stress Test
      script: .ci/scripts/test-stress
    - stage: Mac
      script: .ci/scripts/test-macosx
    - stage: iOS
      script: .ci/scripts/test-ios
    - stage: tvOS
      script: .ci/scripts/test-tvos
